---
title: "Linear Models"
author: "Mari Sanders"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

```{r}
data("nyc_airbnb")

nyc_airbnb <- 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) %>%  
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighborhood, room_type) %>% 
  mutate(
    borough = fct_infreq(borough), 
    room_type = fct_infreq(room_type)
  )


```

# Fit Models 

Simple Model 

```{r}
fit <- lm(price ~ stars, nyc_airbnb)

summary(fit)
names(summary(fit))

coef(fit)

fit %>% 
broom::tidy() %>% 
  select(term, estimate, p.value)

fit %>% 
  broom::glance()
```

More Complex Model 

```{r}
fit <- 
  lm(price ~ stars + borough, data = nyc_airbnb)

fit %>%  
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  mutate(
    term = str_replace(term, "borough", "Borough:")
  ) %>% 
  knitr::kable(digits = 3)
```


# Diagnostics 

EDA
```{r}
nyc_airbnb %>%  
  ggplot(aes(x = stars, y = price)) + 
  geom_point() + 
  stat_smooth(method = "lm")
```

Diagnostics
```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = resid)) + geom_histogram()
```

```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = borough, y = resid)) + 
  geom_violin() +
  ylim(-200, 500)
```


Residuals against stars

```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = stars, y = resid)) + 
  geom_point()
```

Residuals against fitted values

```{r}
nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  modelr::add_predictions(fit) %>% 
  ggplot(aes(x = pred, y = resid)) + 
  geom_point()
```

